### ISSUE TITLE
CatalogBrowser: check on init whether agreement exists

### ISSUE THREAD

**Issue by paullatzelsperger** [agera-edc/DataDashboard#3]
The `CatalogBrowserComponent` should check during initialization whether a contract exists for each offer and act as follows:
- if exists: 
  - re-label the button to `"Re-Negotiate"`
  - add a link to navigate to the agreements page (depends agera-edc/EDCDataDashboard#9)
- if not exists keep as is

**Comment by zeier** [comment]
Moved to upstream
